format = "v1"

[metadata]
desc = "Official CH32V203 & CH32V208 EVT package from WCH"
vendor = { name = "WCH", eula = "" }
upstream_version = "2.2"

[[distfiles]]
name = "CH32V20xEVT-2.2.zip"
size = 48560949
urls = [
  "https://www.wch.cn/download/file?id=385",
]
restrict = "mirror"

[distfiles.checksums]
sha256 = "92ec4011db51c4a4d594354a24b43355ffc1bf038b48a83472aa6f249aea9277"
sha512 = "f742d0179254e5e319fb1248647e299d5b11a4135b6966e9e330eb839a115d9922ff340b5c533fa7854d96459485408283a07c2416190b3ad49ce5a05b02b92d"

[source]
distfiles = ["CH32V20xEVT-2.2.zip"]
