format = "v1"

[metadata]
desc = "Official Bianbu Desktop Lite v2.2.1 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.2.1"

[[distfiles]]
name = "bianbu-24.04-desktop-lite-k1-v2.2.1-release-20250815215854.zip"
size = 2070036074
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.2.1/bianbu-24.04-desktop-lite-k1-v2.2.1-release-20250815215854.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "78e38f60a68f1e24bbe5db92dfbd10fa2c0e2397e4a2deaff45a90f5201c1ca3"
sha512 = "f8a80f3b2268b368de295b57a3b7ab71c4ddb9b72ac385c6ce5b46d1b8fac60c7850628871d2a2d8ab0d04371a6275e232cad4c8bbc523292fb5ec3b66529e82"

[blob]
distfiles = [
  "bianbu-24.04-desktop-lite-k1-v2.2.1-release-20250815215854.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
