format = "v1"

[metadata]
desc = "Official Bianbu Desktop Lite v3.0 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v3.0"

[[distfiles]]
name = "bianbu-25.04-desktop-lite-k1-v3.0-release-20250725124256.zip"
size = 2011046621
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v3.0/bianbu-25.04-desktop-lite-k1-v3.0-release-20250725124256.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "cb48f824ee3053b6ee9160ced43cce0db9195b8435ca929692628700e28e961f"
sha512 = "d6785f6abc5814025f61ec2963ae2062847578ddfa425314dc9e90696c96deff2655676fcc2c74a876252226b30efda48829b23869b81d2611127e6b33b67b84"

[blob]
distfiles = [
  "bianbu-25.04-desktop-lite-k1-v3.0-release-20250725124256.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
