format = "v1"

[metadata]
desc = "U-Boot image for Milk-V Meles (Single-rank, 4G RAM), for RevyOS, 20251226"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "u-boot-with-spl-meles-4g.bin"
size = 780992
urls = [
  "mirror://revyos/extra/images/meles/20251226/u-boot-with-spl-meles-4g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "5792c91e83f79f3db0983cc8192bbe4dc4b6e5e0a04e765f5b71848d49897086"
sha512 = "2fef7ca7cb5a9a7b23b94369c24dc26bea026a4d146e218918ec5e0e69e14f1eaabc7ff91b3a0366560b1c3730ce22e48470cb45770e5ad3d37b402d1d144f69"

[blob]
distfiles = [
  "u-boot-with-spl-meles-4g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles-4g.bin"
