format = "v1"

[metadata]
desc = "U-Boot image for LicheePi 4A (16G RAM) and RevyOS 20251226"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "u-boot-with-spl-lpi4a-16g.bin"
size = 993256
urls = [
  "mirror://revyos/extra/images/lpi4a/20251226/u-boot-with-spl-lpi4a-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "9796b19706eed24517d575d7ade698f0ef9c37b8fd7f9a79eb14c7a42b5fe1ab"
sha512 = "95a62fce62cca6d0ce5a53a111081b47b23b6e35072a27690f282eb48827cbeadfac77950a1d5df2096a9e298e976c5592622b910374ab86e8ce86c9ebb2e132"

[blob]
distfiles = [
  "u-boot-with-spl-lpi4a-16g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-lpi4a-16g.bin"
