format = "v1"

[metadata]
desc = "Official CH32V103 EVT package from WCH"
vendor = { name = "WCH", eula = "" }
upstream_version = "2.7"

[[distfiles]]
name = "CH32V103EVT-2.7.zip"
size = 15736636
urls = [
  "https://www.wch.cn/download/file?id=326",
]
restrict = "mirror"

[distfiles.checksums]
sha256 = "68a1d55e7202634d0e791b2ef1587039c08792dcefb6f84dd1ed568dcb92cee3"
sha512 = "71f665dcb8716f7b8d74f62ee9f550953756675cc4551c11b8f3fd2f33349d40a0cb553083232142f953736a4f1789c4db67f9861c3ef7b9ccdfde1bf324979b"

[source]
distfiles = ["CH32V103EVT-2.7.zip"]
