format = "v1"

[metadata]
desc = "U-Boot image for Lichee Book 4A (16G RAM) and RevyOS 20240720"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20240720"

[[distfiles]]
name = "u-boot-with-spl-laptop4a-16g.bin"
size = 1032040
urls = [
  "mirror://revyos/extra/images/laptop4a/20240720/u-boot-with-spl-laptop4a-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "779d2fc08e8a5a75fa3defdffc0967e6972582be9d54324f6a30b1d49072d51e"
sha512 = "f9d5f14d4d754003791c807eade93da659e06a1ace3ca3e778153228307009d976278f318d9f0faabe65103b1b700c317c80f7ab84841abfc937bd8d203f66a6"

[blob]
distfiles = [
  "u-boot-with-spl-laptop4a-16g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-laptop4a-16g.bin"
