format = "v1"

[metadata]
desc = "U-Boot image for Lichee Book 4A (16G RAM) and RevyOS 20251226"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "u-boot-with-spl-laptop4a-16g.bin"
size = 1032600
urls = [
  "mirror://revyos/extra/images/laptop4a/20251226/u-boot-with-spl-laptop4a-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "0dcf749a6e7068055c83417412fbd8658ec8489748d09ec43f9c27b21f44d413"
sha512 = "b0d08ae0b8c582da2c1ec128d6e001e756503f092fe232358acdbb618843287460d5b61e5125bd3a24852b41ed8e457fc2928e3a873442aefbc5df58ee6d0a43"

[blob]
distfiles = [
  "u-boot-with-spl-laptop4a-16g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-laptop4a-16g.bin"
