format = "v1"

[metadata]
desc = "U-Boot image for Lichee Book 4A (16G RAM) and RevyOS 20251030"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251030"

[[distfiles]]
name = "u-boot-with-spl-laptop4a-16g.bin"
size = 1032200
urls = [
  "mirror://revyos/extra/images/laptop4a/20251030/u-boot-with-spl-laptop4a-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "69fbd73fcc2a5cea62b024a6ada3e16fb9f09e7a63f693ada44553186e69e5e1"
sha512 = "98980b46404bb91a0847e72a9613b590c7b3d82c55a19db088393e8b597e3ac4bb60637b9736c4d8dfb89a7db9d366e3fedabdb45135f21071cda4306191d2ef"

[blob]
distfiles = [
  "u-boot-with-spl-laptop4a-16g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-laptop4a-16g.bin"
