format = "v1"

[metadata]
desc = "Official Bianbu Desktop v3.0 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v3.0"

[[distfiles]]
name = "bianbu-25.04-desktop-k1-v3.0-release-20250725125828.zip"
size = 2596798751
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v3.0/bianbu-25.04-desktop-k1-v3.0-release-20250725125828.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "2a81576b480716f371a704a77912f27954d89ff2ef2f3907c6ff839f28769094"
sha512 = "5221355686728b27de6146fb3f5f58065168239e910c8b06d10f984744d788aeb7923b436dc6debdac45bc492f29861dbfd845ec0cde6d427aff84bdd53f1ca1"

[blob]
distfiles = [
  "bianbu-25.04-desktop-k1-v3.0-release-20250725125828.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
