format = "v1"

[metadata]
desc = "RedleafOS 20250922 image for Xiangshan Nanhu"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250922"

[[distfiles]]
name = "debian-nanhuv2-20250922-155014.img.zst"
size = 1381711863
urls = [
  "https://mirror.iscas.ac.cn/redleafos/extra/images/20250922/debian-nanhuv2-20250922-155014.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "75adf6ff17b7a87c0bc0211db992c24d46a414a0281806eb5190dd653df82505"
sha512 = "2054a2b04d09162e4fe06df6fa6ba7a9ef36f4fe2ebd3af6532087079d1e194df15c08b69c8d2d2acb74b7c875ef8568c4480ea046340781ad23aad993c82f54"

[blob]
distfiles = [
  "debian-nanhuv2-20250922-155014.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "debian-nanhuv2-20250922-155014.img"
