ruyi-repo = "v1"

[repo]
doc_uri = "https://ruyisdk.github.io/docs/"
id = "ruyisdk"

[[telemetry]]
id = "ruyisdk-hq-pm"
scope = "pm"
url = "https://api.ruyisdk.cn/telemetry/pm/"

[[mirrors]]
id = "ruyi-dist"
urls = [
  "https://mirror.iscas.ac.cn/ruyisdk/dist/",
]

[[mirrors]]
id = "ruyi-3rdparty-canaan"
urls = [
  "https://mirror.iscas.ac.cn/ruyisdk/3rdparty/canaan/",
]

[[mirrors]]
id = "ruyi-3rdparty-milkv"
urls = [
  "https://mirror.iscas.ac.cn/ruyisdk/3rdparty/milkv/",
]
