format = "v1"

[metadata]
desc = "Official Arduino SDK image for Milk-V Duo (64M RAM, SD card)"
vendor = { name = "Milk-V", eula = "" }

[[distfiles]]
name = "arduino-milkv-duo-sd-v1.1.2-2024-0801.ruyi1.img.zst"
size = 54381827
urls = [
  "mirror://ruyi-3rdparty-milkv/repacks/arduino-milkv-duo-sd-v1.1.2-2024-0801.ruyi1.img.zst",
]
restrict = "mirror"

[distfiles.checksums]
sha256 = "0f0f79a9d9b3dd765dab2b9cfcb7febfe188f6fbfc847dee349efe34b791e52c"
sha512 = "c05ca6c2f9d13150b12c168336a677f1510f4c9a5ec56cff40a884d5f5ae0af6a4636a10f1b66276f4ff2e36496ea6f15af32b45393f6a9d38a8781f8c221b2f"

[blob]
distfiles = [
  "arduino-milkv-duo-sd-v1.1.2-2024-0801.ruyi1.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "arduino-milkv-duo-sd-v1.1.2-2024-0801.ruyi1.img"
