format = "v1"

[metadata]
desc = "RevyOS 20251030 image for Sipeed Lichee Book 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251030"

[[distfiles]]
name = "boot-laptop-20251030_153344.ext4.zst"
size = 46346732
urls = [
  "mirror://revyos/extra/images/laptop4a/20251030/boot-laptop-20251030_153344.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "f2c6a0eef64a4cbc4211da27e6136feb1fba14db3d1eaf870128490534b5c84c"
sha512 = "f456759617feec3a96e6625103b0d381c184e444b98f71ba9e8254fc7402c5ba55babbe1272b7b990bbf7d9cc6b848195868e9ba6013bc3943116849db093e37"

[[distfiles]]
name = "root-laptop-20251030_153344.ext4.zst"
size = 1343927705
urls = [
  "mirror://revyos/extra/images/laptop4a/20251030/root-laptop-20251030_153344.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "85bfc920b8c0d18fecb2e4851789f776b37f12222f1262745da8d16edf4dae13"
sha512 = "2bb2f9d1ef326da32312c0655a92e3c4137038436b0e7b944ca50f428dc846958ccd462e2c369f52d9f0232e4393bbcd5e4cf143799de00c309c2e05e7b5c0ec"

[blob]
distfiles = [
  "boot-laptop-20251030_153344.ext4.zst",
  "root-laptop-20251030_153344.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-laptop-20251030_153344.ext4"
root = "root-laptop-20251030_153344.ext4"
