format = "v1"

[metadata]
desc = "RevyOS 20250930 image for Sipeed Lichee Book 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250930"

[[distfiles]]
name = "boot-laptop-20250930_113343.ext4.zst"
size = 74694741
urls = [
  "mirror://revyos/extra/images/laptop4a/20250930/boot-laptop-20250930_113343.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "9185f5fb61b999edc8b7b7dc7129390c5f41dd90dd102fcb38b2489f991f1e91"
sha512 = "17d51d0803d5f84e5cfe06b8e1d6d7ae8e7b3e7d7dfd94bcd1dd1258730a1acd1868d72a72d913b9db1f47f24de10b1f6314d541c6d68a5ab7113b8042cb45ae"

[[distfiles]]
name = "root-laptop-20250930_113343.ext4.zst"
size = 1378218041
urls = [
  "mirror://revyos/extra/images/laptop4a/20250930/root-laptop-20250930_113343.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "bc271917a4f23aa63f36ae1aa478fe48b2efdb0a4a2dcdb5fc85c544574ca611"
sha512 = "882dbf31a20565221504402b4ae7018f6092a6b7a15e03fe55b9593dca676c89b989203c2927993f9852364c1452c1b9412ee7dfc76df6a8743aae8c5b93fbef"

[blob]
distfiles = [
  "boot-laptop-20250930_113343.ext4.zst",
  "root-laptop-20250930_113343.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-laptop-20250930_113343.ext4"
root = "root-laptop-20250930_113343.ext4"
