format = "v1"

[metadata]
desc = "RevyOS 20251115 image for Sipeed Lichee Book 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251115"

[[distfiles]]
name = "boot-laptop-20251115_072651.ext4.zst"
size = 46332801
urls = [
  "mirror://revyos/extra/images/laptop4a/20251115/boot-laptop-20251115_072651.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "71eea3a144ad3fb0733076a5ef4fa63e057f04bb48340d2d2c1b644c42b21356"
sha512 = "6a847350ea5850eba299795a8c2856374da74908e70fa9ee929ea91250159ba307ee4a8580fdff3fd8803155f660eb7d0500c3a4957590f19c9e0b5cf58a1aef"

[[distfiles]]
name = "root-laptop-20251115_072651.ext4.zst"
size = 1359357490
urls = [
  "mirror://revyos/extra/images/laptop4a/20251115/root-laptop-20251115_072651.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "42c1eced03aab68ac703b393946a3b2c42afb731710459a719211cbcfa081908"
sha512 = "1a389c5bd9e0753e9115fb3645dc5b80ec042413a2b938ffb3b9cf06ed76c9c807192f35dbac526bd3fd018d6d3cb6ed4606cce5a437e025a843f8084ef645fa"

[blob]
distfiles = [
  "boot-laptop-20251115_072651.ext4.zst",
  "root-laptop-20251115_072651.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-laptop-20251115_072651.ext4"
root = "root-laptop-20251115_072651.ext4"
