format = "v1"

[metadata]
desc = "RevyOS 20240720 image for Sipeed Lichee Book 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20240720"

[[distfiles]]
name = "boot-laptop-20240720_171948.ext4.zst"
size = 28615663
urls = [
  "mirror://revyos/extra/images/laptop4a/20240720/boot-laptop-20240720_171948.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "ebb5d69498fbd3e698d1273625d876dd713e0129cedb2ef7db700c9ec5967b81"
sha512 = "bb69dd109aeb4032767d84dce05edbae97b6344c2d64e7cd7ecad79f048fd378c0cfde3b727fb6042caae143444f1be57b4551570bde65220e6d9462515fb148"

[[distfiles]]
name = "root-laptop-20240720_171948.ext4.zst"
size = 1259877342
urls = [
  "mirror://revyos/extra/images/laptop4a/20240720/root-laptop-20240720_171948.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "93cd36a6919a937e41916dda9a29a1d15e0560be239e053dd6ae11e542bd48eb"
sha512 = "bba43b2c327c27ee89fac04b1017b621206ae46b33f9a78e8d4ee6bec961f02e4aadd3c7a1ba43c7421acf03b88626b521d846166869ce9a4fc84be5694bd42a"

[blob]
distfiles = [
  "boot-laptop-20240720_171948.ext4.zst",
  "root-laptop-20240720_171948.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-laptop-20240720_171948.ext4"
root = "root-laptop-20240720_171948.ext4"
