format = "v1"

[metadata]
desc = "RevyOS 20251226 image for Sipeed Lichee Book 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "boot-laptop-20251225_175320.ext4.zst"
size = 40789542
urls = [
  "mirror://revyos/extra/images/laptop4a/20251226/boot-laptop-20251225_175320.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "f58bd1650cb9cf4a45719f130995522717cb790b2d42a259e00eddc9f5e63624"
sha512 = "9d3199d93629913c579d5b54a2a6f812155ff747a59adbca911cf62f932669536b31e98bec41426f8555b0a27e8a4b963710c0966344430f3dc65de42def533c"

[[distfiles]]
name = "root-laptop-20251225_175320.ext4.zst"
size = 1325297327
urls = [
  "mirror://revyos/extra/images/laptop4a/20251226/root-laptop-20251225_175320.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "4e6c6575cb179ae7ef36f59f68f54d6a7e99029868abc136a82019eb0d113abc"
sha512 = "b37be0a32553f0c78c80c77a8005792e90b8b63159469e9dda988a1347166400c7ae635d3a44af8fdbafbdb41fc117ec4bf579cc82ed8a40e16bc98f59e99c85"

[blob]
distfiles = [
  "boot-laptop-20251225_175320.ext4.zst",
  "root-laptop-20251225_175320.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-laptop-20251225_175320.ext4"
root = "root-laptop-20251225_175320.ext4"
