format = "v1"

[metadata]
desc = "RevyOS 20251025 image for Sipeed Lichee Book 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251025"

[[distfiles]]
name = "boot-laptop-20251025_114742.ext4.zst"
size = 46347480
urls = [
  "mirror://revyos/extra/images/laptop4a/20251025/boot-laptop-20251025_114742.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "554d5b9b41a8e7ce8c3f524be3aa97d62ecca7d62bf7bdd5c63e02aaf1a8f234"
sha512 = "72d3d76a5e4de6e659b7dbe3de6e4536bcbd25358c4688bfcc0be6941f2b41a915130fe45e6d8c0525ce57cba3a98689e9679a37441f6254e1a42dcc12c6ff99"

[[distfiles]]
name = "root-laptop-20251025_114742.ext4.zst"
size = 1341431836
urls = [
  "mirror://revyos/extra/images/laptop4a/20251025/root-laptop-20251025_114742.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "48d7207c65ee0c39106a6bcbf0cde008915d39a81890c4e73d136f84f2a705ff"
sha512 = "4960a07a1a49b2fb7923123508150ac3dcb32e6ab83c6f40c2285b13df720ac69836445de17d810f5e054c315c22939e64e9a79bbb26c117186965779b695887"

[blob]
distfiles = [
  "boot-laptop-20251025_114742.ext4.zst",
  "root-laptop-20251025_114742.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-laptop-20251025_114742.ext4"
root = "root-laptop-20251025_114742.ext4"
