format = "v1"

[metadata]
desc = "RevyOS 20250930 image for Sipeed Lichee Console 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250930"

[[distfiles]]
name = "boot-console-20250930_113115.ext4.zst"
size = 74702120
urls = [
  "mirror://revyos/extra/images/lcon4a/20250930/boot-console-20250930_113115.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "9377c0af3f5b4986657a2287d63669c1e0c69669061bb8d5ad49b157c5957abc"
sha512 = "1d96b8e094c3a2ce77ebe45940ef964aa69f6e3c44d246c74ce9a42c3c49d416aeb264e22128134358c2b571207d21f5174c1875baeab310b89f5ef0bf891333"

[[distfiles]]
name = "root-console-20250930_113115.ext4.zst"
size = 1376135394
urls = [
  "mirror://revyos/extra/images/lcon4a/20250930/root-console-20250930_113115.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "f615b323d63af66d9686d96b2158e2f0de9523ad7c7abb81773a35cb65bfde92"
sha512 = "ebfe25ee8dbc6a2954c2f47724a69ba8db1bc4b65b2e3beba04e2fe7aa78b2ea55c05d1fc3af6352b1b76819a151727aa164d467b4bc048250b68cc6f1b21484"

[blob]
distfiles = [
  "boot-console-20250930_113115.ext4.zst",
  "root-console-20250930_113115.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-console-20250930_113115.ext4"
root = "root-console-20250930_113115.ext4"
