format = "v1"

[metadata]
desc = "RevyOS 20251030 image for Sipeed Lichee Console 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251030"

[[distfiles]]
name = "boot-console-20251030_152917.ext4.zst"
size = 46371316
urls = [
  "mirror://revyos/extra/images/lcon4a/20251030/boot-console-20251030_152917.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "3c4c8a1236f1cd75bc2b3b4cc5fa056058c99a07c557fcef147dbdfa1b145ec2"
sha512 = "f7f8d732ce44d1b500960331f959e155251aa7bef2d48e3136da620ec5cb6d7daccab270edc55527582d2aa72309cef599961ff553d66da7e4cfb8b49089f5ce"

[[distfiles]]
name = "root-console-20251030_152917.ext4.zst"
size = 1343979378
urls = [
  "mirror://revyos/extra/images/lcon4a/20251030/root-console-20251030_152917.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "1d4c172dcd6ecbfd5afc48aa67228aa0b98d248a11580ac1656eae5e25edbcac"
sha512 = "1290781537c1d8cf28dfecd73a9e9fb42e43bf15a457f815434c21a64091858db906959d06738cd7428ba1da692ee62a69b7bbed9f0904ec53eb8a299d629f7f"

[blob]
distfiles = [
  "boot-console-20251030_152917.ext4.zst",
  "root-console-20251030_152917.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-console-20251030_152917.ext4"
root = "root-console-20251030_152917.ext4"
