format = "v1"

[metadata]
desc = "RevyOS 20251115 image for Sipeed Lichee Console 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251115"

[[distfiles]]
name = "boot-console-20251115_072637.ext4.zst"
size = 46331614
urls = [
  "mirror://revyos/extra/images/lcon4a/20251115/boot-console-20251115_072637.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "907dca396b98caffe4679a28bf30c536d4f97dc671b24b2a54fbeb7091ef9a35"
sha512 = "5808225d979fb441edcda2cef5f4a0af4e5633febb23bc793cf48d6507bb7161e849d6e1ea70f4896190a2bbaa5de2af76252af1ab8cdbd004a9d7de21eb710b"

[[distfiles]]
name = "root-console-20251115_072637.ext4.zst"
size = 1341099064
urls = [
  "mirror://revyos/extra/images/lcon4a/20251115/root-console-20251115_072637.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "3eeb001e1d448312719f76096d8584f9290187e686a3073aff3dedbddd7f1559"
sha512 = "bcb42a58274977c9fbea35086b32f7824d7393bc3cec1195c6a0fc40e6151d1c8631a66de81971ae08942e222fa01642d111ab015edf4be651d2b41406f3aae2"

[blob]
distfiles = [
  "boot-console-20251115_072637.ext4.zst",
  "root-console-20251115_072637.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-console-20251115_072637.ext4"
root = "root-console-20251115_072637.ext4"
