format = "v1"

[metadata]
desc = "RevyOS 20240720 image for Sipeed Lichee Console 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20240720"

[[distfiles]]
name = "boot-console-20240720_171948.ext4.zst"
size = 28603659
urls = [
  "mirror://revyos/extra/images/lcon4a/20240720/boot-console-20240720_171948.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "c456d8c4f04282fa11240823703302dcd1b844684d3f3ee4ac3d34f3d82b1fd8"
sha512 = "d8b78502a7f306c57a210e25aff63f1ee7375c58544da6b4babb4caf22ac54ebc92fad7de74381951dadbc0adb0d8854d817f31770001eaf6c31b8213a005f31"

[[distfiles]]
name = "root-console-20240720_171948.ext4.zst"
size = 1258529083
urls = [
  "mirror://revyos/extra/images/lcon4a/20240720/root-console-20240720_171948.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "8d055aaf00196a43f5362ff551775dc67fab8512a39f4a300e44c95148bce459"
sha512 = "afa83322d20d7b4fd84847109b0ed9497257359de3c60225935ce2ade57b33d78af3b7c177f8be492a6d079f3644522a98859beab9799514996fe4fc90f0862f"

[blob]
distfiles = [
  "boot-console-20240720_171948.ext4.zst",
  "root-console-20240720_171948.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-console-20240720_171948.ext4"
root = "root-console-20240720_171948.ext4"
