format = "v1"

[metadata]
desc = "RevyOS 20251226 image for Sipeed Lichee Console 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "boot-console-20251225_175318.ext4.zst"
size = 40789932
urls = [
  "mirror://revyos/extra/images/lcon4a/20251226/boot-console-20251225_175318.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "d14ab481a44d67d7d12d3a413c70989e532a348f0913fed01106acf416f57d6c"
sha512 = "75cfc2266dbbf391a7149689070ea6faf7f777098025fa01ae1d349de43ed7f141b644ae04254798957733a11ea82c23c7c18661408812292f1609a3c3351601"

[[distfiles]]
name = "root-console-20251225_175318.ext4.zst"
size = 1317530095
urls = [
  "mirror://revyos/extra/images/lcon4a/20251226/root-console-20251225_175318.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "54ebbb9a1160ef0bb39488bdb4ce69cb4e4c2a4da5a5094485ae69933f90a1e4"
sha512 = "811cc49dd7dc0dd51de95ef15218dd12db7160822c48a01ef14ba3d36f77e4ce6a284fa3ea3519a49bd7f1560b73164bd2e74b49e563fd329333ea22fae21ac9"

[blob]
distfiles = [
  "boot-console-20251225_175318.ext4.zst",
  "root-console-20251225_175318.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-console-20251225_175318.ext4"
root = "root-console-20251225_175318.ext4"
