format = "v1"

[metadata]
desc = "Official Bianbu Desktop v2.2 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.2"

[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.2-release-20250430190125.zip"
size = 2639790326
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.2/bianbu-24.04-desktop-k1-v2.2-release-20250430190125.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "57dc320094c6b4e427ab40b39b4419cb5a6080fd913c63db8ccd56eba244bf0b"
sha512 = "5049de37bc91f1dfbb635b3bf470d03f4655829232d3a57c54a263efb9579d345733acaa1c2e3357bf2f48f0300cc1273bafc5aabe369daa15e6f15e58d7a1f8"

[blob]
distfiles = [
  "bianbu-24.04-desktop-k1-v2.2-release-20250430190125.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
