format = "v1"

[metadata]
desc = "Official Bianbu Desktop v3.0.1 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v3.0.1"

[[distfiles]]
name = "bianbu-25.04-desktop-k1-v3.0.1-release-20250815185656.zip"
size = 2601164447
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v3.0.1/bianbu-25.04-desktop-k1-v3.0.1-release-20250815185656.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "7741ed172743d8b6b9cf31594353df7188e0a07ba8f8fb70b0a85007276e9143"
sha512 = "26af574cadd9c1ad82cfdd46b77ca5c97fc5c3b04c1a5b3854fd994ab85f61ae06bd336eddab9041edd08bcb81d8dc99228d962d4bf485aa4a74d307f3756014"

[blob]
distfiles = [
  "bianbu-25.04-desktop-k1-v3.0.1-release-20250815185656.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
