ruyi-entity = "v0"

related = [
  "device-variant:sipeed-laptop4a@8g",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "RevyOS for Sipeed Lichee Book 4A (8G RAM)"
package_atoms = [
  "board-image/revyos-sipeed-laptop4a",
  "board-image/uboot-revyos-sipeed-laptop4a-8g"
]
