ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc", "device:milkv-mars"]
unique_among_type_during_traversal = true

[device-variant]
id = "generic"
variant_name = "generic variant"
