ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc", "device:milkv-meles"]
unique_among_type_during_traversal = true

[device-variant]
id = "8g"
variant_name = "8G RAM"
