ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc", "device:milkv-meles"]
unique_among_type_during_traversal = true

[device-variant]
id = "4g"
variant_name = "4G RAM"
