ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc", "device:milkv-pioneer"]
unique_among_type_during_traversal = true

[device-variant]
id = "v1.3"
variant_name = "v1.3"
