format = "v1"

[metadata]
desc = "RockOS 20250630_20250818 image for Milk-V Megrez with EIC7700"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250630_20250818"

[[distfiles]]
name = "sdcard-rockos-20250818-234921.img.zst"
size = 2620924052
urls = [
  "https://mirror.iscas.ac.cn/rockos/images/generic/20250630_20250818/sdcard-rockos-20250818-234921.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "faa463fe559aeacd8ac6425efdfaeb084b713aba22df4e2be0bca0256be86a53"
sha512 = "71710a922c2494200f664805257d775ccba638112d4f015208b7d8be19df77fc8ad8302dd889f09cfdb1359ffe8f2666de50b35a53c93bfc5453ac47795b9db6"

[blob]
distfiles = [
  "sdcard-rockos-20250818-234921.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "sdcard-rockos-20250818-234921.img"
