format = "v1"

[metadata]
desc = "RockOS 20250130_20250219 image for Milk-V Megrez with EIC7700"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250130_20250219"

[[distfiles]]
name = "sdcard-rockos-20250219-091803.img.zst"
size = 2640132503
urls = [
  "https://mirror.iscas.ac.cn/rockos/images/generic/20250130_20250219/sdcard-rockos-20250219-091803.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "8d179a046f190c51a8bc97246f9dc5fe5183c5f599d6f327e7d7a18b83e12fb8"
sha512 = "d717e70fd18209ff9ec056ad8e6006f146f7204ed6e20e2664581ab705ed205c84ef898bacb2d4bcf97fb521f5a92f3993e7115d7ee0d0ba9f62b69f9e4840f5"

[blob]
distfiles = [
  "sdcard-rockos-20250219-091803.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "sdcard-rockos-20250219-091803.img"
