format = "v1"

[metadata]
desc = "GNU toolchain for RISC-V, including GCC (fork maintained by PLCT)"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "riscv-gnu-toolchain-507206248e7944c8eb7ac76d099ba1efaaa2961b.src.tar.zst"
size = 612414134

[distfiles.checksums]
sha256 = "35cd338ddbaddbfa11d93434ba8a9b48d71f96f7a96b579bda701b89d6fa8df2"
sha512 = "755d3dba6057f31611e46f785af0a2d03167a66f0395a5891eca5e3d7cafed7750380b85328b9afcafedee299a69b4e99cca80e3e354f5c530b70abde6e08451"

[source]
distfiles = ["riscv-gnu-toolchain-507206248e7944c8eb7ac76d099ba1efaaa2961b.src.tar.zst"]
