format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo S v1.0.9-2024-0226 (SD card)"
vendor = { name = "Milk-V", eula = "" }

[[distfiles]]
name = "milkv-duos-sd-v1.0.9-2024-0226.img.zip"
size = 53785785
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.0.9/milkv-duos-sd-v1.0.9-2024-0226.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "bb22131db022830b39451d978e5d56dc4df4e2d1dabc97879ef0814fcbd3b8ad"
sha512 = "26cc28540d45b24605279c9414fa0abe7700572790e0cf8f2b7869beba27dc49bfdcd501b1fa3b87561cc6f11ac3a53bb32fb5391d2614a580c6fd29011ff0b9"

[blob]
distfiles = [
  "milkv-duos-sd-v1.0.9-2024-0226.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duos-sd-v1.0.9-2024-0226.img"
