format = "v1"

[metadata]
desc = "Official CH32V30x & CH32V317 EVT package from WCH"
vendor = { name = "WCH", eula = "" }
upstream_version = "2.8"

[[distfiles]]
name = "CH32V307EVT-2.8.zip"
size = 46759980
urls = [
  "https://www.wch.cn/download/file?id=356",
]
restrict = "mirror"

[distfiles.checksums]
sha256 = "1c077ceb9ae3787a86ac99abdf04c80a9b15a17f0b8995c56a9b22c8ade6239e"
sha512 = "f7df12e708502405006d5498de4a4d63ec5682becf09593d93846edd7885d2b169fb459032b09c33cba0dc3a60e58536037b6198655f9e019207a0e1266d0148"

[source]
distfiles = ["CH32V307EVT-2.8.zip"]
