format = "v1"

[metadata]
desc = "U-Boot image for LicheePi 4A (8G RAM) and RevyOS 20251226"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "u-boot-with-spl-lpi4a.bin"
size = 1032824
urls = [
  "mirror://revyos/extra/images/lpi4a/20251226/u-boot-with-spl-lpi4a.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "27312d7cae9a6089631d63964c8be2c78db6e5a538390d6f70691a34bf472d90"
sha512 = "05dbb8772a38993d30b069786d7a5bf17664daf781d3e14a88444a314249fdf767a6ca1c353c8a58ac31a87ec104914a03f14ae3ef8dab75300cace7b0ca87b4"

[blob]
distfiles = [
  "u-boot-with-spl-lpi4a.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-lpi4a.bin"
