format = "v1"

[metadata]
desc = "CanMV Linux SDK image for Canaan Kendryte K230D, built by PLCT, RV64LP64 ABI, with demos"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "kendryte-k230d-linux-sdk-demo.lp64.20240717.ext4.img.zst"
size = 47347328
urls = [
  "mirror://ruyi-3rdparty-canaan/temp/kendryte-k230d-linux-sdk-demo.lp64.20240717.ext4.img.zst",
]
restrict = "mirror"

[distfiles.checksums]
sha256 = "9101cb63d55f90933fa9d248362e08cfcbd18dd95a07bf627252e1b6f0d06eae"
sha512 = "1ca602a931e1fbf38de2460110c281f8d5fefb08dafe1e0cae67fb064067717452b13bb5259a5599b141bf0e4cfa0dc0a67add3afb86529db1b0f1f59ffafc05"

[blob]
distfiles = [
  "kendryte-k230d-linux-sdk-demo.lp64.20240717.ext4.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "kendryte-k230d-linux-sdk-demo.lp64.20240717.ext4.img"
