format = "v1"

[metadata]
desc = "U-Boot image for LicheePi 4A (8G RAM) and RevyOS 20251115"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251115"

[[distfiles]]
name = "u-boot-with-spl-lpi4a-main.bin"
size = 1032312
urls = [
  "mirror://revyos/extra/images/lpi4a/20251115/u-boot-with-spl-lpi4a-main.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "a9b57cfbd4ffaa5031aa39e1e22eaa8169654712e41f7ad5ae453d22da8e0807"
sha512 = "fd2389e3e3a8198f56a56711d8f662ab07c0f8851927111ae4b6e5d1e22cd66419d0ea5e362eb1622ebd0b424480c10dfda1833494a1b30e203b2724d33d987c"

[blob]
distfiles = [
  "u-boot-with-spl-lpi4a-main.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-lpi4a-main.bin"
