format = "v1"

[metadata]
desc = "RevyOS 20251226 image for Milk-V Meles"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "boot-meles-20251225_175245.ext4.zst"
size = 62572400
urls = [
  "mirror://revyos/extra/images/meles/20251226/boot-meles-20251225_175245.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "d5f61c943c3b7d23319f0b90ce9d3f25e9ca60426f83db0435b4a6abf8eb1335"
sha512 = "7bcafb891f251bd05f4007b8bd55748374669f01f4772630e444cfa48695c18a434ec786577fe837a334d7a54c8e9b669abb904ced319849d61366ba4e985e78"

[[distfiles]]
name = "root-meles-20251225_175245.ext4.zst"
size = 1326373897
urls = [
  "mirror://revyos/extra/images/meles/20251226/root-meles-20251225_175245.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "8fb02ef51a85567b785e8cab14c275e7d186e0a7f43ca952eae47f6dd1ff27e5"
sha512 = "db03f3d8e034ab938e5265cf20acb85d8615191de1d3fc5e615860dac0613a00f46453cd9163d9c614c9b0ef8d907c2091cf8b8a356e5788f5862bebad5828d5"

[blob]
distfiles = [
  "boot-meles-20251225_175245.ext4.zst",
  "root-meles-20251225_175245.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-meles-20251225_175245.ext4"
root = "root-meles-20251225_175245.ext4"
