format = "v1"

[metadata]
desc = "RevyOS 20250729 image for Milk-V Meles"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250729"

[[distfiles]]
name = "boot-meles-20250728_180948.ext4.zst"
size = 74507868
urls = [
  "mirror://revyos/extra/images/meles/20250729/boot-meles-20250728_180948.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "64d65a95d774b90b3d643c227e334f5497e670dc46f57aecb626c357e969780b"
sha512 = "4983b8e3fcadcb13f408a7183fbb46680a3790c406803d5e739a8d1f8d5626e2557f6b9fc1b8fd1869b6c3b6d7dbceefe74be56a47e4c5edc02c4fa1f2118133"

[[distfiles]]
name = "root-meles-20250728_180948.ext4.zst"
size = 1363864022
urls = [
  "mirror://revyos/extra/images/meles/20250729/root-meles-20250728_180948.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "c1ccfcc8d5ae44865e4be0176718acad5192a6243f4e82d4575a61cf0b07b14b"
sha512 = "9f92b195e2e2a761d6527a6a3d6cbeab735fe37ab10571c6151e787bda6cb56cc9edbc71d82d3170d4c92e12ec983c804e80c453e86c643a7743c718b119e7f8"

[blob]
distfiles = [
  "boot-meles-20250728_180948.ext4.zst",
  "root-meles-20250728_180948.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-meles-20250728_180948.ext4"
root = "root-meles-20250728_180948.ext4"
