format = "v1"

[metadata]
desc = "RevyOS 20250930 image for Milk-V Meles"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250930"

[[distfiles]]
name = "boot-meles-20250930_113131.ext4.zst"
size = 74728822
urls = [
  "mirror://revyos/extra/images/meles/20250930/boot-meles-20250930_113131.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "7d65dfd1f90293acdd3dafac1ddf8774137ab5f76db17fdb44740c7f28b8a47a"
sha512 = "6441e3d0ff5ff409d147b0a158fe07ce42edf03a4142cd61e34b33d3bd348dc667a87c5ef3cd1d6ec47527a50a4d1f2ecbd115d8ef3e733edc6a677002054c79"

[[distfiles]]
name = "root-meles-20250930_113131.ext4.zst"
size = 1350259412
urls = [
  "mirror://revyos/extra/images/meles/20250930/root-meles-20250930_113131.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "8ecb58b1c76ce7687f6840a9219433293e189572f2f779ac4ffb624293eaf98f"
sha512 = "31284b7f2f2ec14ac4312d566aa6b73f01cc7af0e7e2896b790ea288dd4726b830f6895cc5dbbe7a2681bbe34514303970f30b17ec4c14332ced9932cb40783f"

[blob]
distfiles = [
  "boot-meles-20250930_113131.ext4.zst",
  "root-meles-20250930_113131.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-meles-20250930_113131.ext4"
root = "root-meles-20250930_113131.ext4"
