format = "v1"

[metadata]
desc = "RevyOS 20251115 image for Milk-V Meles"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251115"

[[distfiles]]
name = "boot-meles-20251115_072702.ext4.zst"
size = 73504991
urls = [
  "mirror://revyos/extra/images/meles/20251115/boot-meles-20251115_072702.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "b5c698e8230f0a6575059d57800baeba7673252646511a625b02deab50178bc8"
sha512 = "978627216399465d723aaa6cc3f631a40afcebee2aa88aa6948b9cab4dfc9ef5542059fdaadf524b35ad7e690be233ae475e7ce2cb2105dfbcfa2fd7054a5298"

[[distfiles]]
name = "root-meles-20251115_072702.ext4.zst"
size = 1350225247
urls = [
  "mirror://revyos/extra/images/meles/20251115/root-meles-20251115_072702.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "7cad4ac0315064bc1234a6b985bdee6557730629e62ce9765f87879cbfdb32ad"
sha512 = "4d22793f6e28fa138e0ce794a7fb5faf69e6f23bde215316569bf04996ebe21186b6789c9b72e9fdd88322a8acb522758e01af42e1c0968f0bbb63bb5e579ef0"

[blob]
distfiles = [
  "boot-meles-20251115_072702.ext4.zst",
  "root-meles-20251115_072702.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-meles-20251115_072702.ext4"
root = "root-meles-20251115_072702.ext4"
