format = "v1"

[metadata]
desc = "CanMV Linux SDK image for Canaan Kendryte K230D, built by PLCT, RV64ILP32 ABI, with demos"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "kendryte-k230d-linux-sdk-demo.rv64ilp32.20240717.ext4.img.zst"
size = 47254860
urls = [
  "mirror://ruyi-3rdparty-canaan/temp/kendryte-k230d-linux-sdk-demo.rv64ilp32.20240717.ext4.img.zst",
]
restrict = "mirror"

[distfiles.checksums]
sha256 = "9b8afa3f52ba8b59675824376e4fb11cf84c2c10a82c769ea8086d29d90082db"
sha512 = "9d783ad8810bb5179c5df9493349ca82ddcaafb46ef63dd382d75103ffd0590a10a449a916407c14bc22b1e3cd157021a2fecda6000f4a5ea06813470748ca6a"

[blob]
distfiles = [
  "kendryte-k230d-linux-sdk-demo.rv64ilp32.20240717.ext4.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "kendryte-k230d-linux-sdk-demo.rv64ilp32.20240717.ext4.img"
