format = "v1"

[metadata]
desc = "U-Boot image for Milk-V Meles (Dual-rank, 8G RAM), for RevyOS, 20251226"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "u-boot-with-spl-meles.bin"
size = 780992
urls = [
  "mirror://revyos/extra/images/meles/20251226/u-boot-with-spl-meles.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "4d62bee0ab5fd44b707680fe6e73dc3855349f53214a7eea1612402576273703"
sha512 = "00088436a62c2bb42af05d0db6d7fc3383320fa03f554a1e9639ed07f1f4a1a303d5afcd629d699212c91eb90ae75fcb7f5ff50c64971540ec2cfd5c2a705f75"

[blob]
distfiles = [
  "u-boot-with-spl-meles.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles.bin"
