format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo S v1.1.0-2024-0410 (SD card)"
vendor = { name = "Milk-V", eula = "" }

[[distfiles]]
name = "milkv-duos-sd-v1.1.0-2024-0410.img.zip"
size = 54377170
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.1.0/milkv-duos-sd-v1.1.0-2024-0410.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "3c600cd9c7c6370cecbade176636a3ee513c880593963aa5cf5a5efb0e2227bd"
sha512 = "40d21591005e717eb25c6731c9c8dbe0571dfc866ff1a16e4c8cdcc661015f6ebe96ae35d9889141227b815b07d81aade58f5ba4ef6a20bac3180066d9231dc3"

[blob]
distfiles = [
  "milkv-duos-sd-v1.1.0-2024-0410.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duos-sd-v1.1.0-2024-0410.img"
