format = "v1"

[metadata]
desc = "Official OpenWRT 24.10.3 image for SiFive Unmatched"
vendor = { name = "OpenWrt", eula = "" }
upstream_version = "24.10.3"

[[distfiles]]
name = "openwrt-24.10.3-sifiveu-generic-sifive_unmatched-ext4-sdcard.img.gz"
size = 9369469
urls = [
  "https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/24.10.3/targets/sifiveu/generic/openwrt-24.10.3-sifiveu-generic-sifive_unmatched-ext4-sdcard.img.gz",
  "https://downloads.openwrt.org/releases/24.10.3/targets/sifiveu/generic/openwrt-24.10.3-sifiveu-generic-sifive_unmatched-ext4-sdcard.img.gz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "e186227479e325122246c82bb3ca7df3e73997fd5973056f2e8272a235df888e"
sha512 = "97397ebe803b0e0347052d231890f2cf7a402ddc53a7333994ef3ffefaf0733ac5332f316a53ef332597ab47700cc57fbe4f034b48e368b56f36192da7b036c3"

[blob]
distfiles = [
  "openwrt-24.10.3-sifiveu-generic-sifive_unmatched-ext4-sdcard.img.gz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "openwrt-24.10.3-sifiveu-generic-sifive_unmatched-ext4-sdcard.img"
