format = "v1"

[metadata]
desc = "U-Boot image for Sipeed Lichee Console 4A (16G RAM) and RevyOS 20250729"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250729"

[[distfiles]]
name = "u-boot-with-spl-lcon4a-16g.bin"
size = 1032072
urls = [
  "mirror://revyos/extra/images/lcon4a/20250729/u-boot-with-spl-lcon4a-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "8b0ea688e332c3581e655befc19a20ce46be5ed3c645f2a21f52f090df3bfc6d"
sha512 = "ba6825ec4a4e6656a8bf511845bac3c2a7a71a00bc438dad625044b7b8ac88a8cd6928dd6c45609fdd70b6c264d9cc59fa392c0a639fe09526514ea903b21749"

[blob]
distfiles = [
  "u-boot-with-spl-lcon4a-16g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-lcon4a-16g.bin"
