format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo (256M RAM) v1.0.7-2023-1223 (with Python)"
vendor = { name = "Milk-V", eula = "" }

[[distfiles]]
name = "milkv-duo256m-python-v1.0.7-2023-1223.img.zip"
size = 49539010
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.0.7/milkv-duo256m-python-v1.0.7-2023-1223.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "52d0a5bbb70e03eb32bf3dbaa23dd3aff19d5449ce62e101c1d18d794fcc7552"
sha512 = "383c3c358fe5b2f89b4c8aeb877a1609240573a2d484e9f732ea97d38d1001f9652e38826b049c88ca9e5c0c3024e97818a7823340d440445a301eb1ab001b23"

[blob]
distfiles = [
  "milkv-duo256m-python-v1.0.7-2023-1223.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duo256m-python-v1.0.7-2023-1223.img"
