format = "v1"

[metadata]
desc = "RockOS 20241230_20250124 image for Milk-V Megrez with EIC7700"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20241230_20250124"

[[distfiles]]
name = "sdcard-rockos-20250123-210346.img.zst"
size = 2593414846
urls = [
  "https://mirror.iscas.ac.cn/rockos/images/generic/20241230_20250124/sdcard-rockos-20250123-210346.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "b364ed826a1caf1e996f6aab8f6d5759b061a135c15ee3653d5883c50fd522d1"
sha512 = "b4c9e6b95e65d799116e26b2ad0e05128b82a09d09643d772253c45dfbce20382aa83f8856accf912c3e6fc69a137c29711fa4869da398ef21c6ede2de4dd644"

[blob]
distfiles = [
  "sdcard-rockos-20250123-210346.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "sdcard-rockos-20250123-210346.img"
