format = "v1"

[metadata]
desc = "RockOS 20250530_20250729 image for Milk-V Megrez with EIC7700"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250530_20250729"

[[distfiles]]
name = "sdcard-rockos-20250729-015830.img.zst"
size = 2592843420
urls = [
  "https://mirror.iscas.ac.cn/rockos/images/generic/20250530_20250729/sdcard-rockos-20250729-015830.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "c1595812ade462a68c88c473f5672400a4c2906f75b6f4c4e23d58140b139e49"
sha512 = "8d22a99f1b406ce7f0db7ae21b868d23d9c85e418f3c86dbdb987069d9945d3324e609737e911752faa557c85938eeb8e97e667aad502c163dd26fd64c60c386"

[blob]
distfiles = [
  "sdcard-rockos-20250729-015830.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "sdcard-rockos-20250729-015830.img"
