format = "v1"

[metadata]
desc = "RockOS 20241230_20250117 image for Milk-V Megrez with EIC7700"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20241230_20250117"

[[distfiles]]
name = "sdcard-rockos-20250117-223529.img.zst"
size = 2564076810
urls = [
  "https://mirror.iscas.ac.cn/rockos/images/generic/20241230_20250117/sdcard-rockos-20250117-223529.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "bccd4dacc00f97d4958f5c1f5cea6b78d8614b7c5eff1bc02d929c4f462d081c"
sha512 = "c6cffc7c71d1a148feb3d9c60222f99c34eb5ce2d1a87188fd709c5fdefc88957efe50793372b9792abce01966f83d8391fe21a832ec157cac054fd43d43f65e"

[blob]
distfiles = [
  "sdcard-rockos-20250117-223529.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "sdcard-rockos-20250117-223529.img"
