format = "v1"

[metadata]
desc = "RockOS 20250330_20250423 image for Milk-V Megrez with EIC7700"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250330_20250423"

[[distfiles]]
name = "sdcard-rockos-20250423-145338.img.zst"
size = 2623463396
urls = [
  "https://mirror.iscas.ac.cn/rockos/images/generic/20250330_20250423/sdcard-rockos-20250423-145338.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "c5bae1cb077c02934fb3b2544e54c7872371275474cdc87828b1ebb0f74ee81b"
sha512 = "310bd2f98e6b0322b85a8d66c63cbd76cdb3a8df912d6503e916f66e6e6a755b1ec589c5880d30d54c73bd6d78722eac36803d3f9d95b74ce1f81ecddd99f63f"

[blob]
distfiles = [
  "sdcard-rockos-20250423-145338.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "sdcard-rockos-20250423-145338.img"
