format = "v1"

[metadata]
desc = "RuyiSDK RISC-V Linux GNU Toolchain 20260201 (Upstream sources, built by RuyiSDK)"
vendor = { name = "RuyiSDK", eula = "" }

[[distfiles]]
name = "RuyiSDK-20260201-Upstream-Sources-HOST-aarch64-linux-gnu-riscv64-unknown-linux-gnu.tar.xz"
size = 173350660

[distfiles.checksums]
sha256 = "f5d66a514cb4a37750ddd5ed6c9dd4424398f1ac582ca105c949fffaefea2766"
sha512 = "b97eeb04e74c9c1913d84dc307beb2a7ba0c7e6d7b7ada9f0efaa6257a4c144d9bbcaee380f4f103474d54ca15f43bb8b16c3b78a910b2aac1ee883d5ee873a2"

[[distfiles]]
name = "RuyiSDK-20260201-Upstream-Sources-HOST-riscv64-linux-gnu-riscv64-unknown-linux-gnu.tar.xz"
size = 179467756

[distfiles.checksums]
sha256 = "a55a642238df84bfbb069d28b1cb5380d4fd5ea058e102ec4051494a12974c3d"
sha512 = "c533677ba9f1cf7f514bb7cdc9e566e4ab375982f05c725c2b87bfa143030089bdea737aa225cac477bcdaf2dce4d4b7b90bd948833d080f3e80b7428c273bc4"

[[distfiles]]
name = "RuyiSDK-20260201-Upstream-Sources-riscv64-unknown-linux-gnu.tar.xz"
size = 185877284

[distfiles.checksums]
sha256 = "621717aa242f97d16c3349334df59217f62bb072184953f7e888d89951bed0de"
sha512 = "1e7e0246e519b8cbd0f59ded6543473d2573518f96fcc245b2a7a8fb829c8995fb83097f059256971ea1dcc7c2af0516b70bf2109b9c6b0761030d108b503f26"

[[binary]]
host = "aarch64"
distfiles = ["RuyiSDK-20260201-Upstream-Sources-HOST-aarch64-linux-gnu-riscv64-unknown-linux-gnu.tar.xz"]

[[binary]]
host = "riscv64"
distfiles = ["RuyiSDK-20260201-Upstream-Sources-HOST-riscv64-linux-gnu-riscv64-unknown-linux-gnu.tar.xz"]

[[binary]]
host = "x86_64"
distfiles = ["RuyiSDK-20260201-Upstream-Sources-riscv64-unknown-linux-gnu.tar.xz"]

[toolchain]
target = "riscv64-unknown-linux-gnu"
flavors = []
components = [
  { name = "binutils", version = "2.45" },
  { name = "gcc", version = "15.2.0" },
  { name = "gdb", version = "16.3" },
  { name = "glibc", version = "2.43" },
  { name = "linux-headers", version = "6.18.3" },
]
included_sysroot = "riscv64-unknown-linux-gnu/sysroot"
