format = "v1"

[metadata]
desc = "RuyiSDK RISC-V Bare-metal RV64ILP32 GNU Toolchain (maintained by PLCT)",
"vendor": { name = "PLCT", eula = "" }

[[distfiles]]
name = "RuyiSDK-20240906-PLCT-Sources-RV64ILP32-gdf9313313b45-HOST-aarch64-linux-gnu-riscv64-plct-elf.tar.xz"
size = 42480636

[distfiles.checksums]
sha256 = "a2e429e4e06dabf2555cc2bfad984e7ebf30fbbe18438dc5a666bd13469ebbe6"
sha512 = "2ddad46fe096cdd737cbee9230fd4ac6b219cb26780edd293141e35a1d79ac3df8a3d8d54253c458fe624a97a188a9e19e0ee600ef2cedc165181a6358e178e3"

[[distfiles]]
name = "RuyiSDK-20240906-PLCT-Sources-RV64ILP32-gdf9313313b45-HOST-riscv64-linux-gnu-riscv64-plct-elf.tar.xz"
size = 44882184

[distfiles.checksums]
sha256 = "1d75aa6e026cebd5ffad10c3eda3e7f48cbd70cbc90e357fa2db09fb9ae1f722"
sha512 = "eb583379a2ed65f57cb400b2eec18c5873cc12dd4f0d66918ceee2a2d45a60d64ff5ea16ce80d8cc4e02fe4796d2dfaf5c248a679ee39a9a4dc92344e3f94035"

[[distfiles]]
name = "RuyiSDK-20240906-PLCT-Sources-RV64ILP32-gdf9313313b45-riscv64-plct-elf.tar.xz"
size = 49568148

[distfiles.checksums]
sha256 = "a5767fda8aac203a3623a18839f85e9b5da9eac652b5eb6eb72ecd40ca9363b6"
sha512 = "40ab81a65624d70a2795be7b6bee3c918c8a178dfe5fbdc8b205c9221941b22ded37180fe93cb1058fb254344a17bd50bfe8d048a939812074166d0c3a379352"

[[binary]]
host = "aarch64"
distfiles = ["RuyiSDK-20240906-PLCT-Sources-RV64ILP32-gdf9313313b45-HOST-aarch64-linux-gnu-riscv64-plct-elf.tar.xz"]

[[binary]]
host = "riscv64"
distfiles = ["RuyiSDK-20240906-PLCT-Sources-RV64ILP32-gdf9313313b45-HOST-riscv64-linux-gnu-riscv64-plct-elf.tar.xz"]

[[binary]]
host = "x86_64"
distfiles = ["RuyiSDK-20240906-PLCT-Sources-RV64ILP32-gdf9313313b45-riscv64-plct-elf.tar.xz"]

[toolchain]
target = "riscv64-plct-elf"
flavors = ["rv64ilp32"]
components = [
  { name = "binutils", version = "2.42" },
  { name = "gcc", version = "13.2.0" },
  { name = "gdb", version = "14.1" },
]
