format = "v1"

[metadata]
desc = "U-Boot image for Sipeed Lichee Console 4A (16G RAM) and RevyOS 20251226"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "u-boot-with-spl-lcon4a-16g.bin"
size = 1032600
urls = [
  "mirror://revyos/extra/images/lcon4a/20251226/u-boot-with-spl-lcon4a-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "d95cf91be61761f68b9eb3afdd16bfda2478b0b0ef6aeb56124f63ee954b5ca9"
sha512 = "ef288e46a4843510229912a3ed61f5d8603c39340151597c7193ac5ed2b47f883e44019c967288bc0026df5928407d0a764c44266f5780301c534113a76951db"

[blob]
distfiles = [
  "u-boot-with-spl-lcon4a-16g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-lcon4a-16g.bin"
