format = "v1"

[metadata]
desc = "Official Bianbu Desktop Lite v2.2 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.2"

[[distfiles]]
name = "bianbu-24.04-desktop-lite-k1-v2.2-release-20250430185050.zip"
size = 1867534799
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.2/bianbu-24.04-desktop-lite-k1-v2.2-release-20250430185050.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "d468ef4304035d318a334307b041c3eaa83e20bc8a13c03e400a423c24da2f59"
sha512 = "7a77f0b55f5d02420a5739c8ebd378d99d4b514e1f419f9533c27a66b1543c322a69d6f06fd52b9ec4ed3d90e7329d27f62102a7a3fc2de333156337e9327218"

[blob]
distfiles = [
  "bianbu-24.04-desktop-lite-k1-v2.2-release-20250430185050.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
