format = "v1"

[metadata]
desc = "Official Bianbu Desktop Lite v3.0.1 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v3.0.1"

[[distfiles]]
name = "bianbu-25.04-desktop-lite-k1-v3.0.1-release-20250815184229.zip"
size = 2015510957
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v3.0.1/bianbu-25.04-desktop-lite-k1-v3.0.1-release-20250815184229.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "d1cb60c194e024ded0908ac9ff67e60608995d572d2b8c1642e997e7fb034de7"
sha512 = "429eae4ed2c30884be681d2a0d987dfb1f76ddf62116a16544b4f9f49c94a3ad55650bf7dc7ff80cf0912435f0dcead03a28177bfe8a2ea490cb6c745265ece2"

[blob]
distfiles = [
  "bianbu-25.04-desktop-lite-k1-v3.0.1-release-20250815184229.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
