format = "v1"

[metadata]
desc = "Official Ubuntu 24.04.3 Server image for SiFive HiFive Unmatched"
vendor = { name = "Ubuntu", eula = "" }
upstream_version = "24.04.3"

[[distfiles]]
name = "ubuntu-24.04.3-preinstalled-server-riscv64+unmatched.img.xz"
size = 1083910496
urls = [
  "mirror://ubuntu-cdimage/releases/24.04/release/ubuntu-24.04.3-preinstalled-server-riscv64+unmatched.img.xz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "f385868c2870c4d16213bcfee50e9bd168400f34df1b4b6b3f6ceae19acd59de"
sha512 = "98e620555c8e0ef9d31a56e6a583a28fa5498198f483d4c87e881ebde0513b6b2e3b4a18fc762f88c0f77e006cf1807e2148f9bfc557faddf48ae2ab676d8093"

[blob]
distfiles = [
  "ubuntu-24.04.3-preinstalled-server-riscv64+unmatched.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "ubuntu-24.04.3-preinstalled-server-riscv64+unmatched.img"
