format = "v1"

[metadata]
desc = "Official Ubuntu 25.04 Server image for SiFive HiFive Unmatched"
vendor = { name = "Ubuntu", eula = "" }
upstream_version = "25.04"

[[distfiles]]
name = "ubuntu-25.04-preinstalled-server-riscv64+unmatched.img.xz"
size = 1127903608
urls = [
  "mirror://ubuntu-cdimage/releases/25.04/release/ubuntu-25.04-preinstalled-server-riscv64+unmatched.img.xz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "d784207ffd037f0f20a42b9f70615019f6d027de0f09511baadee2c23075a9fc"
sha512 = "249247867ab9ee703131531c4e349035fbde0ae01b973088012c4a50110754e83209f576e556735251905e1d341afc25aa54d8189d81fba93d682580314d253c"

[blob]
distfiles = [
  "ubuntu-25.04-preinstalled-server-riscv64+unmatched.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "ubuntu-25.04-preinstalled-server-riscv64+unmatched.img"
