ruyi-entity = "v0"

related = ["device-variant:bananapi-bpi-f3@sd", "device-variant:bananapi-bpi-f3@emmc"]
unique_among_type_during_traversal = true

[device]
id = "spacemit-musebox"
display_name = "SpacemiT MUSE Box"
