format = "v1"

[metadata]
desc = "RevyOS 20251226 image for Milk-V Pioneer Box with SG2042"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "revyos-pioneer-20251226-002451.img.zst"
size = 4631363899
urls = [
  "mirror://revyos/extra/images/sg2042/20251226/revyos-pioneer-20251226-002451.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "8f0f05643840b6163082af84bb48c947ecdc933e2ee4dc504f7b23a4699e34ec"
sha512 = "7fd6527a5a2c3da29e93837c2917ce8bed61ddd4ff21cd345110aef7d491e10f1fde6408065c9ddb750ca13c5a5642f6d301641454cca2b147f7adb86b630370"

[blob]
distfiles = [
  "revyos-pioneer-20251226-002451.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "revyos-pioneer-20251226-002451.img"
