format = "v1"

[metadata]
desc = "RevyOS 20230924 image for Milk-V Pioneer Box with SG2042"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20230924"

[[distfiles]]
name = "revyos-sg2042-20230924-181457.img"
size = 7516192768
urls = [
  "https://mirror.iscas.ac.cn/revyos/extra/images/sg2042/20230924/revyos-sg2042-20230924-181457.img",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "65cad1f034bca09b8ac1277cb52b0c200589460c66e880dd03767282a09a81af"
sha512 = "ddee65cfffc1d108a06ad283910386181044115b9be10950c38a5861dfd745f6b778a181a26165610f2319f1d5edf1f022db110f9b957197da0a32c95ec91411"

[blob]
distfiles = [
  "revyos-sg2042-20230924-181457.img",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "revyos-sg2042-20230924-181457.img"
