format = "v1"

[metadata]
desc = "RevyOS 20251012 image for Milk-V Pioneer Box with SG2042"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251012"

[[distfiles]]
name = "revyos-pioneer-20251012-190129.img.zst"
size = 1655211403
urls = [
  "mirror://revyos/extra/images/sg2042/20251012/revyos-pioneer-20251012-190129.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "43275a642016220253e3a8e7c5f5eff52f956ce8fba93fa354a9ca38c61dff86"
sha512 = "ab6cb3acb3730ef721a255ef22e944dbda7d688b2a9e4b770c2a647fe9525a6f620d559f0f19738b0e3e87e741ad66cd418e734c0fd94a02ca1437b47654552c"

[blob]
distfiles = [
  "revyos-pioneer-20251012-190129.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "revyos-pioneer-20251012-190129.img"
