format = "v1"

[metadata]
desc = "RevyOS 20240819 image for Milk-V Pioneer Box with SG2042"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20240819"

[[distfiles]]
name = "revyos-pioneer-20240819-154656.img.zst"
size = 1653149108
urls = [
  "https://mirror.iscas.ac.cn/revyos/extra/images/sg2042/20240819/revyos-pioneer-20240819-154656.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "7881f2d5f2583aae32615dc577d145052e91f20864d55911a1d79476232f7cea"
sha512 = "17d986dc57ad4dc259f22168cbd5d3ffad163f0b35461e21f93b1cf77ebc091f45e04dde1d589d40cf9c84d5afc257abf6be6bd97711131afa589be81299795b"

[blob]
distfiles = [
  "revyos-pioneer-20240819-154656.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "revyos-pioneer-20240819-154656.img"
