format = "v1"

[metadata]
desc = "RevyOS 20240716 image for Milk-V Pioneer Box with SG2042"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20240716"

[[distfiles]]
name = "revyos-pioneer-20240716-130625.img.zst"
size = 1542685593
urls = [
  "https://mirror.iscas.ac.cn/revyos/extra/images/sg2042/20240716/revyos-pioneer-20240716-130625.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "8166e91f305fb486819705b1ba148ad2c303f8dedd40f66ba401bebdac7d6cc4"
sha512 = "654e2d790434a2ce3d5119737a1585b6f7395445a8d5a66c3d075d465e96b4dcf4d938a5f2b2288c9feed389f34cf1ab1321c12e8bd16d862199bf884ec11acc"

[blob]
distfiles = [
  "revyos-pioneer-20240716-130625.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "revyos-pioneer-20240716-130625.img"
