format = "v1"

[metadata]
desc = "RevyOS 20251030 image for Milk-V Pioneer Box with SG2042"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251030"

[[distfiles]]
name = "revyos-pioneer-20251030-004123.img.zst"
size = 3415626971
urls = [
  "mirror://revyos/extra/images/sg2042/20251030/revyos-pioneer-20251030-004123.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "c4ce1fb6f9e509343f97677f1550293fb2a948267555b3604ed4a1e0e0d1e745"
sha512 = "c9e03c1013d22117aceffa6ca329699ef002e53c3087f60069bbe060b7fffe2da761f5e0286530ea1aa6ad61c3856f2a0ada18bc5ab6648f808efcb548bb968b"

[blob]
distfiles = [
  "revyos-pioneer-20251030-004123.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "revyos-pioneer-20251030-004123.img"
