format = "v1"

[metadata]
desc = "Official Bianbu Desktop Lite v3.0.1 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v3.0.1"

[[distfiles]]
name = "bianbu-25.04-desktop-lite-k1-v3.0.1-release-20250815184229.img.zip"
size = 2015524307
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v3.0.1/bianbu-25.04-desktop-lite-k1-v3.0.1-release-20250815184229.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "99c0926bd7bd0f74130a8ce4f1ce01cb03b06f19dd6da63f64f5b2b7745bfaeb"
sha512 = "6e76f0dab81151ff91091925bea0ec3b586b41d2e97df4d2480c153d83b2c804a950fb30e4a9344012fb4efdbab944888588d54ee248c721e256e12630f33928"

[blob]
distfiles = [
  "bianbu-25.04-desktop-lite-k1-v3.0.1-release-20250815184229.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "bianbu-25.04-desktop-lite-k1-v3.0.1-release-20250815184229.img"
