format = "v1"

[metadata]
desc = "U-Boot image for Milk-V Meles (Dual-rank, 16G RAM), for RevyOS, 20251226"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "u-boot-with-spl-meles-16g.bin"
size = 780992
urls = [
  "mirror://revyos/extra/images/meles/20251226/u-boot-with-spl-meles-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "0425db98634bb90ef41ddb0faa54293551efecf2fc52075b6e73867f68d7e38f"
sha512 = "dff5e5617db44d6faf4e3643c93c743fcb94385328c235e91aa30d82fea6f1899d5a4c6da448db31d0828f5cdccd461e62361f9176e0f9fdca9022ba7e5b7291"

[blob]
distfiles = [
  "u-boot-with-spl-meles-16g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles-16g.bin"
