format = "v1"

[metadata]
desc = "U-Boot image for Milk-V Meles (Dual-rank, 16G RAM), for RevyOS, 20251115"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251115"

[[distfiles]]
name = "u-boot-with-spl-meles-16g.bin"
size = 780496
urls = [
  "mirror://revyos/extra/images/meles/20251115/u-boot-with-spl-meles-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "1551ae525700dc6352f42b7d5280f9bd9a383f2d2f9dae8b129388c784eed5e0"
sha512 = "90d7413459d232c3321c9661b8b9d3201e6efc0ed9b681bb51ddf433addc3b784704bfa01f9c8e8f8b38cd4e031ebe7899d6d6c3c091e28d3998907ae2b19256"

[blob]
distfiles = [
  "u-boot-with-spl-meles-16g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles-16g.bin"
