format = "v1"

[metadata]
desc = "U-Boot image for Sipeed Lichee Console 4A (8G RAM) and RevyOS 20240720"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20240720"

[[distfiles]]
name = "u-boot-with-spl-lcon4a.bin"
size = 1032040
urls = [
  "mirror://revyos/extra/images/lcon4a/20240720/u-boot-with-spl-lcon4a.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "4c06514f6b173c4a6432e6e911bf8d11e27f5e5a76b0c2e2cb89ddf6cbebc434"
sha512 = "733ea80c492c7e862d7b198f03fa7f6894926a80f3bb06f8bc04a000531bf7a17a111165af27faa5584dce3703cac548679f2954487d96a2810f326e8a94e51c"

[blob]
distfiles = [
  "u-boot-with-spl-lcon4a.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-lcon4a.bin"
