format = "v1"

[metadata]
desc = "RevyOS 20251226 image for Sipeed LicheePi 4A"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "boot-lpi4a-20251225_175338.ext4.zst"
size = 62570786
urls = [
  "mirror://revyos/extra/images/lpi4a/20251226/boot-lpi4a-20251225_175338.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "bd1a380f332cb54826772c6c9978c6511ab3f5926864782b97445bff53446773"
sha512 = "3550dba3c6adbc0e8efe60203fd7a3600dbcb9e9f2fd8d11a83891f413694895e029876edbc7081c3d7241d074ddd2d876d19a098888bebde5a1107b51ce1ef3"

[[distfiles]]
name = "root-lpi4a-20251225_175338.ext4.zst"
size = 1326131822
urls = [
  "mirror://revyos/extra/images/lpi4a/20251226/root-lpi4a-20251225_175338.ext4.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "d0fe66f3a687d9e16046370b74e5fb9d40aa7d389e72fb5ef656144a881040eb"
sha512 = "86ec7754f801e6a58eb11de1dfc5c7b21864045e3e5023a19d682e91241d2dc9370e6086465881c7b0fc0daf7f7f89b7dc3516499cf442a02f79326bc838d291"

[blob]
distfiles = [
  "boot-lpi4a-20251225_175338.ext4.zst",
  "root-lpi4a-20251225_175338.ext4.zst",
]

[provisionable]
strategy = "fastboot-v1"

[provisionable.partition_map]
boot = "boot-lpi4a-20251225_175338.ext4"
root = "root-lpi4a-20251225_175338.ext4"
