format = "v1"

[metadata]
desc = "Official Bianbu Minimal v2.0.1 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.0.1"

[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.0.1-release-20241025234454.zip"
size = 2530677868
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.0.1/bianbu-24.04-desktop-k1-v2.0.1-release-20241025234454.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "26d38f110f4def2db9e0c9356a4bcb2d25c6935d10ee9afbe68154db75221c25"
sha512 = "69138a88e62e7039d395e0bb259fe4dcc8c80a17c249b02ad5dbdb060f07f281c395908eedba8bdd9acda06f520c5f07d570b0ebadb1d39ab404716c1ceef3a7"

[blob]
distfiles = [
  "bianbu-24.04-desktop-k1-v2.0.1-release-20241025234454.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
