format = "v1"

[metadata]
desc = "Official Bianbu Desktop v2.0.4 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.0.4"

[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.0.4-release-20241206002355.zip"
size = 2632524044
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.0.4/bianbu-24.04-desktop-k1-v2.0.4-release-20241206002355.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "70e4c6a23b18686ad86d9b4ea5b3602ef3efa594901d1abaa74325704b7b0b6e"
sha512 = "fd26f6b3b261f7ce55f2f66c6ad4442cdb7a948a00dfecfd3e433ad18d8157ca062bbbd420536f2f345a7054a133bd33ef8720cb82236e3c9c4feb8e1b8afc2d"

[blob]
distfiles = [
  "bianbu-24.04-desktop-k1-v2.0.4-release-20241206002355.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
