format = "v1"

[metadata]
desc = "Official Bianbu Desktop v2.0 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.0"

[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.0-release-20241021195251.zip"
size = 2528985817
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.0/bianbu-24.04-desktop-k1-v2.0-release-20241021195251.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "c5acc94bfd783b4f008d08a92753bcc9434179dd8b6c558b3515bb0e00a855de"
sha512 = "9370c1921ba3fd0eded3000dcf158808368ec4b74f8e6b8aba5022b6712b6d5ce77e19fd8c98fa31c071873f4f55adb57aeabbb2c81c1631bd54edfd36348c24"

[blob]
distfiles = [
  "bianbu-24.04-desktop-k1-v2.0-release-20241021195251.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
