format = "v1"

[metadata]
desc = "Official Bianbu Desktop v2.1.2 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.1.2"

[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.1.2-release-20250421172038.zip"
size = 2575115597
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.1.2/bianbu-24.04-desktop-k1-v2.1.2-release-20250421172038.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "151ef10d7a162e80cf0d91db5dc70953bba33edc406de866afc00941e49a2fee"
sha512 = "fd11323e1c61013671911452f7002f4dc0e3d5aa5bc0a2af6f55de6f0c3224e5e12d9b511c5bac920df84853a31555b50dd2339b87a8bfebeed6cb1ea7b98573"

[blob]
distfiles = [
  "bianbu-24.04-desktop-k1-v2.1.2-release-20250421172038.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
