format = "v1"

[metadata]
desc = "Official Bianbu Desktop v2.1.1 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.1.1"

[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.1.1-release-20250305144026.zip"
size = 2616261133
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.1.1/bianbu-24.04-desktop-k1-v2.1.1-release-20250305144026.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "3da3a0d632330618f705a94c92ff6d4cff724b8eb9ccea65218d447a91cac3bd"
sha512 = "70415ade40571ec9209fb69f6d039e3e1f1b5cc38b8ba5db8a4b035f7256bbd0cb0cfe85a1c7b5b5f52dc90925ca9c46117a191d4817cfc0ee00ce7e8eef7b67"

[blob]
distfiles = [
  "bianbu-24.04-desktop-k1-v2.1.1-release-20250305144026.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
