format = "v1"

[metadata]
desc = "U-Boot image for Lichee Book 4A (8G RAM) and RevyOS 20251226"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251226"

[[distfiles]]
name = "u-boot-with-spl-laptop4a.bin"
size = 1032600
urls = [
  "mirror://revyos/extra/images/laptop4a/20251226/u-boot-with-spl-laptop4a.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "4f7f6b4c3df3d6acab5713c879dcd2e9ff81cac0730c3ae15de0b246440355b7"
sha512 = "63b87259a50eac46c135532ff76a645e993c25f85ddcbcdadd61debfebb34d6ad5691bffbe6b3a462e82932f79b119cf94dfada47f5255a09be65579e19df766"

[blob]
distfiles = [
  "u-boot-with-spl-laptop4a.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-laptop4a.bin"
