format = "v1"

[metadata]
desc = "U-Boot image for Lichee Book 4A (8G RAM) and RevyOS 20251025"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20251025"

[[distfiles]]
name = "u-boot-with-spl-laptop4a.bin"
size = 1032200
urls = [
  "mirror://revyos/extra/images/laptop4a/20251025/u-boot-with-spl-laptop4a.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "084b0430f3895eb6101cad13d720d55d8ba143da4112dd399ec7633b0b4e2e52"
sha512 = "9a8573e7d25070ef77bd1a23c5918eef8e806e77f214ef0fac5ef0185a251b8c74c7705cccfd57f7393bb05512a0628d17494b3e329184f291058969638cd35f"

[blob]
distfiles = [
  "u-boot-with-spl-laptop4a.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-laptop4a.bin"
