format = "v1"

[metadata]
desc = "U-Boot image for Lichee Book 4A (8G RAM) and RevyOS 20240720"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20240720"

[[distfiles]]
name = "u-boot-with-spl-laptop4a.bin"
size = 1032040
urls = [
  "mirror://revyos/extra/images/laptop4a/20240720/u-boot-with-spl-laptop4a.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "33ca362269c908c2693b0aa49ce00d3978c55a9fc533728cdc56de14b292286e"
sha512 = "59827532f69e5f94fec4bf207c17a5114a60ecab566dacd825cfee8d3de0755e6a263e0f1f6a0e1fdef249c34ab1f9dffc35e2f0d93c001840dac3b82ffeb9a9"

[blob]
distfiles = [
  "u-boot-with-spl-laptop4a.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-laptop4a.bin"
