format = "v1"

[metadata]
desc = "Official Bianbu Desktop Lite v2.2 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.2"

[[distfiles]]
name = "bianbu-24.04-desktop-lite-k1-v2.2-release-20250430185050.img.zip"
size = 1867535805
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.2/bianbu-24.04-desktop-lite-k1-v2.2-release-20250430185050.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "c533c5681a198c949942e9198f48047cea3dc0d92ec777ee19b722416149dada"
sha512 = "bd36335fb46f082fed7a1859f21ad7ebbb003be4fa1a49ef45595ae7d5c27de3515a6781b25dfb6a569b7c361a6a22b45aaa6403994bed7dc31f91f45d754599"

[blob]
distfiles = [
  "bianbu-24.04-desktop-lite-k1-v2.2-release-20250430185050.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "bianbu-24.04-desktop-lite-k1-v2.2-release-20250430185050.img"
