format = "v1"

[metadata]
desc = "Official Bianbu Desktop Lite v2.2.1 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.2.1"

[[distfiles]]
name = "bianbu-24.04-desktop-lite-k1-v2.2.1-release-20250815215854.img.zip"
size = 2070040587
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.2.1/bianbu-24.04-desktop-lite-k1-v2.2.1-release-20250815215854.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "c15f58f70a4e3d40d29955295bba340a90781d7da10ed49e5eee7946106514f2"
sha512 = "1a87b4e66036d66c22f06265853091c869c6032783e4fa5d5e5da1e5badf8ec6cc27b30fb1a27864a922694c43a91c95ff8d87201b3eec79c1a06fabb3deb5af"

[blob]
distfiles = [
  "bianbu-24.04-desktop-lite-k1-v2.2.1-release-20250815215854.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "bianbu-24.04-desktop-lite-k1-v2.2.1-release-20250815215854.img"
