format = "v1"

[metadata]
desc = "Official Bianbu Desktop Lite v3.0 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v3.0"

[[distfiles]]
name = "bianbu-25.04-desktop-lite-k1-v3.0-release-20250725124256.img.zip"
size = 2011036411
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v3.0/bianbu-25.04-desktop-lite-k1-v3.0-release-20250725124256.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "9679139db76fcc02447b4f02f0abb65f58f9b23306c0446b2d518ded8b133c05"
sha512 = "3fd5938212c87595d1fd0205efab27e2b645d10dd3f4b567e55cc79106047a494621844fbfa8e1de403ec2944da2b5f0a74da184a3beb2b6bd4f79f4a31eb6dd"

[blob]
distfiles = [
  "bianbu-25.04-desktop-lite-k1-v3.0-release-20250725124256.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "bianbu-25.04-desktop-lite-k1-v3.0-release-20250725124256.img"
