format = "v1"

[metadata]
desc = "RedleafOS 20250927 image for Xiangshan Nanhu"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20250927"

[[distfiles]]
name = "debian-nanhuv2-20250927-224931.img.zst"
size = 1505349297
urls = [
  "https://mirror.iscas.ac.cn/redleafos/extra/images/20250927/debian-nanhuv2-20250927-224931.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "1cf5c0df24260ab4feefb48b00d683e2e86fd61ef15289e660a21b71b2b880e1"
sha512 = "9e704908acdd0abbb06c24d7a6079f492721a722eb0c5b568a83cd256f8b5890a1cb99c011c16226f2fcf3322d71cbbb06ad4f97d9c0028b3f82ba9be677a9a6"

[blob]
distfiles = [
  "debian-nanhuv2-20250927-224931.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "debian-nanhuv2-20250927-224931.img"
