format = "v1"
[[distfiles]]
name = "2025-03-19-15-13-e4e133.img.xz"
size = 145585860
urls = [ "https://github.com/sipeed/LicheeRV-Nano-Build/releases/download/20250319/2025-03-19-15-13-e4e133.img.xz",]
restrict = [ "mirror",]

[distfiles.checksums]
sha256 = "710b4235ba1da752c843bdacc350209032a54e3f4fa3cb42289d7793fe61b46b"
sha512 = "9d7e9f14dcfad4a9a4cfe5dcf8dfbeb966bfbd13b12a4ce4a01188e9912facb649f4411c849c569f6216b9358b79035cfcd74c59ca1e725e4e5e2baa15612f3e"

[metadata]
desc = "buildroot  for LicheeRV Nano with version 20250319"
service_level = []
upstream_version = "20250319"

[blob]
distfiles = [ "2025-03-19-15-13-e4e133.img.xz",]

[provisionable]
strategy = "dd_v1"

[metadata.vendor]
name = "sipeed-licheervnano"
eula = ""

[provisionable.partition_map]
disk = "2025-03-19-15-13-e4e133.img"

# This file is created by program Sync Package Index inside support-matrix
# Run ID: 14392989952
# Run URL: https://github.com/wychlw/support-matrix/actions/runs/14392989952
