format = "v1"

[metadata]
desc = "Official Bianbu Minimal v2.0.2 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.0.2"

[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.0.2-release-20241111222735.zip"
size = 2533707834
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.0.2/bianbu-24.04-desktop-k1-v2.0.2-release-20241111222735.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "137e2ae14d77bd64fa3599826f2c2fbc3e33b9777ce8a97c550175785a54df47"
sha512 = "92460b834d1146f93fc67874d9388dc53d9311e8c103e3c2fe66d665a3e3d21212f9ca0b43c290a3a4f291f664f3891852d02d6d3cb360dccea3e410b53a0ae7"

[blob]
distfiles = [
  "bianbu-24.04-desktop-k1-v2.0.2-release-20241111222735.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
