format = "v1"

[metadata]
desc = "Official Bianbu Minimal v2.1 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.1"

[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.1-release-20250124144655.zip"
size = 2615638690
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.1/bianbu-24.04-desktop-k1-v2.1-release-20250124144655.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "b237bb5610ab5cca16a4534f3e6889c9fcff08009dc5e1e150c7a8e32afe92cf"
sha512 = "8b361252336e6f07abdf4a290d79b99750291964515fdf8d16d01054f743ba2e797d3eaaee595a638fc7943aa88570b17b8832cfaff6f51ee56c683bd2bbaa72"

[blob]
distfiles = [
  "bianbu-24.04-desktop-k1-v2.1-release-20250124144655.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
