format = "v1"

[metadata]
desc = "Official Bianbu Minimal v2.2.1 for SpacemiT K1"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.2.1"

[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.2.1-release-20250815220536.zip"
size = 2644972721
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.2.1/bianbu-24.04-desktop-k1-v2.2.1-release-20250815220536.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "9d7d61fc86075625c9196ffc697a69af34e23d61c01ba4ebe7f7ef5c2d6e82ad"
sha512 = "7aa14d7e823f0af12a25bc8c835723feb923763cf27da055f2376b25224fe0d13f6a05858722a542c51e53d7842f3abe9c4ca6632884d100747e30461aaaf5a3"

[blob]
distfiles = [
  "bianbu-24.04-desktop-k1-v2.2.1-release-20250815220536.zip",
]

[provisionable]
strategy = "spacemit-k1-v1"

[provisionable.partition_map]
bootfs = "bootfs.ext4"
bootinfo = "factory/bootinfo_sd.bin"
env = "env.bin"
fsbl = "factory/FSBL.bin"
gpt = "partition_universal.json"
opensbi = "fw_dynamic.itb"
rootfs = "rootfs.ext4"
uboot = "u-boot.itb"
